export enum ActionType {
    GET_PRODUCT_LIST='get_product_list',
    CHANGE_PRODUCT_LIST='change_product_list',
    SEND_NOW_ON_SHELF = 'send_now_on_shelf',
    SEND_OFF_SHELF = 'send_offShelf',
    GET_SEARCH_LIST = 'get_search_list',
    CHANGE_SEARCH_LIST='change_search_list',
    GET_GOODS_DETAIL='get_goods_detail',
    CHANGE_GOODS_DETAIL='change_goods_detail',
    CHANGE_CURRENT_CASCADE_SELECTION='change_current_cascade_selection',
    DELETE_UPLOAD_IMG='delete_upload_img',
    CHANGE_RICH_TEXT_EDITOR_CONTENT='change_rich_text_editor_content',
    CHANGE_UPLOAD_IMG_PATH='change_upload_img_path',
    ADD_PRODUCT='add_product',
}
